version: '3.8'

services:
  backend:
    build: ./backend
    container_name: mi-formulario-app-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    container_name: mi-formulario-app-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
